version: '3.8'

services:
  ophtha-inference:
    build:
      context: ./Diabetic-Retinopathy  # Path to Triton Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - triton_net
    shm_size: 2g
    restart: always 

  optha-fastapi:
    build:
      context: ./Diabetic-Retinopathy/src/app
      dockerfile: Dockerfile_clientapp
    ports:
      - "8001:8001"
    networks:
      - triton_net
    env_file:
      - .env
    depends_on:
      - ophtha-inference
    restart: always 

networks:
  triton_net:
    driver: bridge
